services:
  lindacraft-server:
    image: marctv/minecraft-papermc-server:latest
    restart: unless-stopped
    container_name: LindaCraft-server
    environment:
      TZ: Europe/Stockholm
      MEMORYSIZE: ${TOTAL_RAM}
      PAPERMC_FLAGS: ${PAPER_FLAGS}
      PUID: "1002"
      PGID: "1002"
      SKIP_PERM_CHECK: ${PERM_CHECK}
    networks:
      local_net:
        ipv4_address: 192.168.100.2
    ports:
      - "25565:25565" # Minecraft port
      - "25565:25565/udp" # For voice chat support
      - "127.0.0.1:8123:8123" # Dynmap
    volumes:
      - ./server:/data
    stdin_open: true
    tty: true

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      PUID: "1002"
      PGID: "1002"
    networks:
      local_net:
        ipv4_address: 192.168.100.3
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data/caddy/conf:/etc/caddy
      - ./data/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      local_net:
        ipv4_address: 192.168.100.5
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      local_net:
        ipv4_address: 192.168.100.6
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://stats.minecraft.lindacarlstad.se/

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host   
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

volumes:
  prometheus_data:
  grafana_data:
  caddy_data:
  caddy_config:
